image: python:latest
definitions:
   steps:
    - step: &build-test
        name: Build and test
        script:
          - pip install flask boto3 requests
          - echo "SUCCESS"

    - step: &deployment
        name: Deployment to ec2
        script: 
          - echo "Deploying to production environment"
          - ls -l
          - pipe: atlassian/scp-deploy:1.3.0
            variables:
                USER: '${USER}'
                SERVER: '${SERVER}'
                REMOTE_PATH: '/home/ec2-user/'
                LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/*'
                

          - pipe: atlassian/ssh-run:0.5.0
            variables:
              SSH_USER: '${USER}'
              SERVER: '${SERVER}'
              COMMAND: 'sudo yum install pip -y; pip install flask boto3 requests' 
              

        

pipelines:
  default:
    - step: *build-test
    - step: 
        <<: *deployment
        deployment: Production

          